name: "Dashify truncate uniquify"
description: "Dashifies a string, adds a suffix to make the result uniq within a desired length."
author: "jost.kuenzel@gmail.com"
inputs:
  input:
    required: true
    description: "string to dashify, truncate, uniquify"
    default: "default value if applicable"
  desiredLength:
    required: true
    description: "desired length of the resulting string."
  suffixLength:
    required: true
    description: "length of suffix if input is longer than desiredLength"
    default: "64"
outputs:
  result:
    description: "Dashified, truncated, uniquified string"
runs:
  using: "node12"
  main: "dist/index.js"
